CCannedObject
{
	Object=CActionExpression
	{
		Action=CAndAction
		{
			Action=Array
			{
				Item Count=3
				Action=CWasQuestEverActivatedAction
				{
					Quest=Levels/Wilderness/Quests/Rid the Dryad's Forest of the Goblins
				}
				Action=CExpressionAction
				{
					Expression=COR
					{
						Operand1=CUseCannedExpression
						{
							Canned Expression=Dialog/Requirements/Skills/Speech/Speech moreequal 20
						}
						Operator=
						Operand2=CUseCannedExpression
						{
							Canned Expression=Dialog/Requirements/Derived Attributes/Outwit 7 greater or equal
						}
					}
					Character to get attributes from=$Instigator
				}
				Action=CNotAction
				{
					Action=CIsQuestCompletedAction
					{
						Quest=Levels/Wilderness/Quests/Slay the River Dryad
					}
				}
			}
			Early Exit=0
		}
	}
	Use=Shared Global Instance
}
