CCannedObject
{
	Object=CInventoryItemGeneratorAdditionalMagic
	{
		Items=Array
		{
			Array Count=1
			Array Item=CInventoryItemGeneratorBasicItem
			{
				Weighting=10
				Item=Inventory Items/ShortSword
			}
		}
		Chance Has Additional Magic=1
		Additional Magic=Array
		{
			Array Count=1
			Array Item=CInventoryItemGeneratorAdditionalMagicItem
			{
				Weighting=10
				Addition=Inventory/Inventory Additions/Weapons/Ratsbane
				Level=0
			}
		}
	}
	Use=Shared Global Instance
}
